In [1]:
import torch
from transformers import BertModel, BertTokenizer

In [11]:
#BERT_MODEL_CLASSES = [BertModel, BertForPreTraining, BertForMaskedLM, BertForNextSentencePrediction,
#                      BertForSequenceClassification, BertForTokenClassification, BertForQuestionAnswering]
#BERT_TOKENIZER     = [BertTokenizer]
#pretrained_weights = 'bert-base-uncased'

In [12]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased', output_hidden_states = True, output_attentions = True )

In [20]:
input_id = torch.tensor([tokenizer.encode("Let's see all hidden-states and attentions on this text", add_special_tokens=True)])
print(input_id)
with torch.no_grad():
    last_hidden_states = model(input_id)
    print("\n*-3=================")
    print(last_hidden_states[-3])
    print("\n*-2=================")
    print(last_hidden_states[-2])
    print("\n*-2=================")
    print(last_hidden_states[-1])
    print("\n*0=================")
    print(last_hidden_states[0])
    print("\n*1=================")
    print(last_hidden_states[1])
    print("\n*2=================")
    print(last_hidden_states[2])

tensor([[ 101, 2292, 1005, 1055, 2156, 2035, 5023, 1011, 2163, 1998, 3086, 2015,
         2006, 2023, 3793,  102]])

*-3=================
tensor([[-8.6399e-01, -3.6869e-01, -6.3717e-01,  6.8478e-01,  3.5074e-01,
         -8.9612e-02,  8.1756e-01,  2.7797e-01, -3.5233e-01, -9.9997e-01,
          5.6518e-02,  5.9613e-01,  9.8416e-01,  3.0330e-01,  9.0972e-01,
         -4.0513e-01,  1.9216e-01, -5.5137e-01,  2.8559e-01, -1.6689e-01,
          6.6712e-01,  9.9968e-01,  4.8424e-01,  3.0882e-01,  4.2468e-01,
          8.6978e-01, -6.2880e-01,  9.3332e-01,  9.5327e-01,  6.9790e-01,
         -6.2212e-01,  2.1331e-01, -9.8564e-01, -1.9426e-01, -7.5005e-01,
         -9.9094e-01,  3.0855e-01, -7.1216e-01,  5.9371e-02,  8.4432e-02,
         -8.7733e-01,  2.5831e-01,  9.9984e-01, -4.3506e-01,  3.3716e-01,
         -2.0643e-01, -9.9999e-01,  1.5783e-01, -8.5203e-01,  3.7749e-01,
          4.2439e-01,  4.1493e-01,  2.0734e-02,  3.7029e-01,  3.1911e-01,
          1.6143e-01, -2.1888e-01,  8.4156e-02, 

(tensor([[[[4.3559e-02, 3.7997e-02, 2.8314e-02,  ..., 8.0878e-02,
           4.4774e-02, 2.1688e-01],
          [6.8319e-02, 1.0475e-02, 7.7015e-02,  ..., 5.9895e-02,
           8.5536e-02, 1.4857e-01],
          [6.6851e-02, 4.5693e-02, 2.9408e-02,  ..., 6.2479e-02,
           6.4475e-02, 1.0662e-01],
          ...,
          [1.1303e-01, 7.4979e-02, 6.5277e-02,  ..., 3.6467e-02,
           6.6151e-02, 4.3756e-02],
          [2.6880e-02, 7.6922e-02, 5.6221e-02,  ..., 9.8508e-02,
           6.3681e-02, 6.0728e-02],
          [6.0352e-02, 3.7828e-02, 3.5805e-02,  ..., 9.9595e-02,
           4.6433e-02, 9.9184e-02]],

         [[3.1167e-01, 4.5014e-03, 1.0096e-01,  ..., 3.6990e-03,
           9.6805e-04, 2.9560e-03],
          [2.8955e-03, 1.0808e-02, 2.5348e-02,  ..., 1.5691e-02,
           3.9391e-01, 2.6842e-02],
          [1.4786e-02, 1.0518e-01, 9.2822e-03,  ..., 3.7016e-02,
           1.1483e-01, 2.8523e-02],
          ...,
          [9.0703e-03, 1.9539e-01, 1.5743e-02,  ..., 1.779

In [2]:
import tensorflow as tf
print(tf.__version__)

ImportError: Traceback (most recent call last):
  File "/home/nb01/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/nb01/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/nb01/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/nb01/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/nb01/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.